# Generated by Django 4.2.2 on 2023-06-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='department',
            field=models.CharField(choices=[('general', 'General'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('general_surgery', 'General Surgery'), ('hematology', 'Hematology'), ('neurology', 'Neurology'), ('obstetrics_gynecology', 'Obstetrics and Gynecology'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('otolaryngology', 'Otolaryngology'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('urology', 'Urology')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=20),
        ),
    ]
