# Generated by Django 4.2.2 on 2023-06-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_record_employee_id_alter_record_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='history',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
