# Generated by Django 4.2.2 on 2023-06-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_record_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='history',
            new_name='history_record',
        ),
    ]
