# Generated by Django 4.2.2 on 2023-06-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_history_record_history_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='history_record',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
